### ISSUE TITLE
Remove @internal PHPDoc

### ISSUE THREAD

**Issue by ellisgl** [tomrf/htmx-message#1]
The '@internal' PHPDoc tag make for some annoyances in some IDEs.
PHPStorm:
![image](https://github.com/tomrf/htmx-message/assets/94559/9ee73283-5d73-4f05-863c-b1a6320e4c1b)

**Comment by tomrf** [comment]
The @internal tag has now been removed from the proxy classes and methods, tagged with version 1.2.0
